/**
 * HomeFarm — Central Variety Data Source
 * ======================================
 * This single file drives: carousel, detail panel, comparison table,
 * ordering CTAs, image alt text, and SEO content.
 *
 * BOTANICAL RESPONSIBILITY:
 * - Brix values are qualified as "reported" ranges
 * - Pollination claims use evidence-based labels
 * - Evidence levels track data confidence
 * - No fabricated yields, timelines, or guarantees
 *
 * WHATSAPP: 917012301716 (verified from existing codebase)
 */

const WHATSAPP_NUMBER = '917012301716';

const varieties = [
  {
    id: 'ecuador-palora-yellow',
    number: 1,
    name: 'Ecuador Palora Yellow',
    nameML: 'ഇക്വഡോർ പലോറ യെല്ലോ',
    character: 'Exceptionally sweet yellow dragon fruit',
    characterML: 'അസാധാരണമായ മധുരമുള്ള മഞ്ഞ ഡ്രാഗൺ ഫ്രൂട്ട്',
    mainFeature: 'High reported sweetness + thorny yellow skin',
    mainFeatureML: 'ഉയർന്ന മധുരം + മുള്ളുള്ള മഞ്ഞ തൊലി',
    skin: 'Yellow, thorny',
    skinML: 'മഞ്ഞ, മുള്ളുള്ള തൊലി',
    flesh: 'Translucent white',
    fleshML: 'സുതാര്യമായ വെളുത്ത ഉൾഭാഗം',
    flavor: 'Floral, pear, honey',
    flavorML: 'പൂവിന്റെ, പേരയുടെ, തേനിന്റെ രുചി',
    brix: '18–22°',
    brixNote: 'Reported range — varies with maturity and conditions',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി — വളർച്ചയും സാഹചര്യങ്ങളും അനുസരിച്ച് വ്യത്യാസപ്പെടും',
    pollination: 'Self-fertile — reported',
    pollinationML: 'സ്വയം പരാഗണം — റിപ്പോർട്ട് ചെയ്തത്',
    evidence: 'HIGH',
    description: 'The Ecuador Palora is renowned worldwide for its exceptional sweetness and unique thorny yellow skin.',
    descriptionML: 'അസാധാരണ മധുരത്തിനും മഞ്ഞ മുള്ളുള്ള തൊലിക്കും ലോകപ്രശസ്തമായ ഇനം.',
    plantNotes: 'Slower-growing compared to red-fleshed types. Thorny stems require careful handling.',
    plantNotesML: 'ചുവന്ന ഇനങ്ങളെ അപേക്ഷിച്ച് വളർച്ച പതുക്കെയാണ്. മുള്ളുള്ള തണ്ടുകൾ ശ്രദ്ധയോടെ കൈകാര്യം ചെയ്യണം.',
    fruitNotes: 'Smaller fruit with thorny exterior. Typically harvested when skin turns fully yellow.',
    fruitNotesML: 'മുള്ളുള്ള ചെറിയ പഴം. തൊലി പൂർണ്ണമായും മഞ്ഞയാകുമ്പോൾ വിളവെടുക്കുന്നു.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/ecuador-palora-yellow-cut.jpg',
    altText: 'Ecuador Palora Yellow dragon fruit cut open showing translucent white flesh with black seeds and yellow thorny skin'
  },
  {
    id: 'makisupa-red',
    number: 2,
    name: 'Makisupa Red',
    nameML: 'മാകിസുപ റെഡ്',
    character: 'Vibrant red with berry-tangy notes',
    characterML: 'ബെറി രുചിയുള്ള ഉജ്ജ്വല ചുവപ്പ്',
    mainFeature: 'Vibrant magenta-red flesh + berry/tangy profile',
    mainFeatureML: 'ഉജ്ജ്വല മജന്ത-ചുവപ്പ് ഉൾഭാഗം + ബെറി രുചി',
    skin: 'Pinkish red',
    skinML: 'പിങ്ക് കലർന്ന ചുവപ്പ്',
    flesh: 'Vibrant magenta-red',
    fleshML: 'ഉജ്ജ്വല മജന്ത-ചുവപ്പ്',
    flavor: 'Berry, tangy-sweet',
    flavorML: 'ബെറി, പുളിമധുരം',
    brix: '14–16°',
    brixNote: 'Reported range',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Cross-pollination recommended',
    pollinationML: 'അന്യ പരാഗണം ശുപാർശ ചെയ്യുന്നു',
    evidence: 'MEDIUM',
    description: 'A vigorous grower producing vibrant red flesh with a balanced, tangy-sweet flavor reminiscent of mixed berries.',
    descriptionML: 'ഉജ്ജ്വല ചുവന്ന ഉൾഭാഗവും സന്തുലിതമായ പുളിമധുരവും ഉള്ള ശക്തമായ ഒരു ഇനം.',
    plantNotes: 'Vigorous grower with strong stem production.',
    plantNotesML: 'ശക്തമായ വളർച്ചയും തണ്ടുകളും.',
    fruitNotes: 'Medium to large fruit with prominent green fins.',
    fruitNotesML: 'പച്ച ചിറകുകളുള്ള ഇടത്തരം മുതൽ വലിയ പഴം വരെ.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/makisupa-red-cut.jpg',
    altText: 'Makisupa Red dragon fruit cut open showing vibrant magenta-red flesh with black seeds'
  },
  {
    id: 'purple-haze',
    number: 3,
    name: 'Purple Haze',
    nameML: 'പർപ്പിൾ ഹേസ്',
    character: 'Deep purple flesh with grape-berry flavor',
    characterML: 'മുന്തിരി രുചിയുള്ള ആഴമുള്ള പർപ്പിൾ',
    mainFeature: 'Deep purple flesh + cross-pollination requirement',
    mainFeatureML: 'ഗാഢമായ പർപ്പിൾ ഉൾഭാഗം + അന്യ പരാഗണം ആവശ്യമാണ്',
    skin: 'Pink-red',
    skinML: 'പിങ്ക്-ചുവപ്പ്',
    flesh: 'Deep purple',
    fleshML: 'ആഴമുള്ള പർപ്പിൾ',
    flavor: 'Grape, berry',
    flavorML: 'മുന്തിരി, ബെറി രുചി',
    brix: '16–19°',
    brixNote: 'Reported range',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Self-incompatible — requires cross-pollination',
    pollinationML: 'സ്വയം പരാഗണമില്ല — അന്യ പരാഗണം ആവശ്യമാണ്',
    evidence: 'MEDIUM',
    description: 'A visually striking variety with deep purple flesh and a complex grape-berry flavor.',
    descriptionML: 'ആഴത്തിലുള്ള പർപ്പിൾ ഉൾഭാഗവും മുന്തിരിയുടെയും ബെറിയുടെയും സങ്കീർണ്ണ രുചിയുമുള്ള ആകർഷകമായ ഇനം.',
    plantNotes: 'Good vigor. Requires companion varieties for pollination.',
    plantNotesML: 'നല്ല വളർച്ച. പരാഗണത്തിന് മറ്റ് ഇനങ്ങൾ ആവശ്യമാണ്.',
    fruitNotes: 'Medium-sized fruit with distinctive purple coloring throughout.',
    fruitNotesML: 'വ്യതിരിക്തമായ പർപ്പിൾ നിറമുള്ള ഇടത്തരം പഴം.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/purple-haze-cut.jpg',
    altText: 'Purple Haze dragon fruit cut open showing deep purple flesh with black seeds'
  },
  {
    id: 'mexican-red',
    number: 4,
    name: 'Mexican Red',
    nameML: 'മെക്സിക്കൻ റെഡ്',
    character: 'Classic red-fleshed variety, mildly sweet',
    characterML: 'ക്ലാസിക് ചുവന്ന ഉൾഭാഗം, സൗമ്യ മധുരം',
    mainFeature: 'Classic red-fleshed variety with earthy undertones',
    mainFeatureML: 'മണ്ണിന്റെ രുചിയുള്ള ക്ലാസിക് ചുവന്ന ഇനം',
    skin: 'Red-pink',
    skinML: 'ചുവപ്പ്-പിങ്ക്',
    flesh: 'Red to dark-red',
    fleshML: 'ചുവപ്പ് മുതൽ ഇരുണ്ട ചുവപ്പ്',
    flavor: 'Mild, sweet',
    flavorML: 'സൗമ്യ മധുരം',
    brix: '14–17°',
    brixNote: 'Reported range — may vary by clone',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി — ക്ലോൺ അനുസരിച്ച് വ്യത്യാസപ്പെടും',
    pollination: 'Reports vary by clone',
    pollinationML: 'ക്ലോൺ അനുസരിച്ച് വ്യത്യാസപ്പെടും',
    evidence: 'MEDIUM',
    description: 'A classic red-fleshed variety known for robust growth and dependable mildly sweet fruit.',
    descriptionML: 'ശക്തമായ വളർച്ചയ്ക്കും വിശ്വസനീയമായ സൗമ്യ മധുരമുള്ള ഫലങ്ങൾക്കും പ്രശസ്തമായ ക്ലാസിക് ചുവന്ന ഇനം.',
    plantNotes: 'Robust grower. Good for beginners.',
    plantNotesML: 'ശക്തമായ വളർച്ച. തുടക്കക്കാർക്ക് അനുയോജ്യം.',
    fruitNotes: 'Medium to large fruit. Characteristics selection-dependent.',
    fruitNotesML: 'ഇടത്തരം മുതൽ വലിയ പഴം വരെ. ഗുണനിലവാരം ക്ലോൺ അനുസരിച്ച് മാറും.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/mexican-red-cut.jpg',
    altText: 'Mexican Red dragon fruit cut open showing red flesh with black seeds'
  },
  {
    id: 'moroccan-red',
    number: 5,
    name: 'Moroccan Red',
    nameML: 'മൊറോക്കൻ റെഡ്',
    character: 'Warm-climate red with earthy sweetness',
    characterML: 'ചൂടുള്ള കാലാവസ്ഥയ്ക്ക് അനുയോജ്യം, മണ്ണിന്റെ മധുരം',
    mainFeature: 'Excellent warm-climate performance + firm red flesh',
    mainFeatureML: 'ചൂടുള്ള കാലാവസ്ഥയിൽ മികച്ച വളർച്ച + ഉറച്ച ചുവന്ന ഉൾഭാഗം',
    skin: 'Red',
    skinML: 'ചുവപ്പ്',
    flesh: 'Red',
    fleshML: 'ചുവപ്പ്',
    flavor: 'Earthy, sweet',
    flavorML: 'മണ്ണിന്റെ, മധുരം',
    brix: '16–18°',
    brixNote: 'Reported range',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Reports vary by clone',
    pollinationML: 'ക്ലോൺ അനുസരിച്ച് വ്യത്യാസപ്പെടും',
    evidence: 'MEDIUM',
    description: 'A vigorous red variety that performs exceptionally well in warm climates with an earthy sweetness.',
    descriptionML: 'ചൂടുള്ള കാലാവസ്ഥയിൽ നന്നായി വളരുന്ന ശക്തമായ ചുവന്ന ഇനം.',
    plantNotes: 'Vigorous. Performs well in warm Indian climates.',
    plantNotesML: 'ശക്തമായ വളർച്ച. ചൂടുള്ള കാലാവസ്ഥയിൽ നന്നായി വളരുന്നു.',
    fruitNotes: 'Medium to large, firm flesh.',
    fruitNotesML: 'ഇടത്തരം മുതൽ വലിയ പഴം, ഉറച്ച ഉൾഭാഗം.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/moroccan-red-cut.jpg',
    altText: 'Moroccan Red dragon fruit cut open showing red flesh with black seeds'
  },
  {
    id: 'malaysian-red',
    number: 6,
    name: 'Malaysian Red',
    nameML: 'മലേഷ്യൻ റെഡ്',
    character: 'Deep red with rich, earthy flavor',
    characterML: 'ഗാഢമായ ചുവപ്പ്, സമ്പന്നമായ രുചി',
    mainFeature: 'Highly pigmented deep red fruit + strong tropical growth',
    mainFeatureML: 'ഗാഢമായ ചുവപ്പ് നിറമുള്ള പഴം + മികച്ച ഉഷ്ണമേഖലാ വളർച്ച',
    skin: 'Red',
    skinML: 'ചുവപ്പ്',
    flesh: 'Deep red',
    fleshML: 'ഗാഢമായ ചുവപ്പ്',
    flavor: 'Rich, earthy',
    flavorML: 'സമ്പന്നം, മണ്ണിന്റെ സ്വഭാവം',
    brix: '15–18°',
    brixNote: 'Reported range',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Reports vary by clone',
    pollinationML: 'ക്ലോൺ അനുസരിച്ച് വ്യത്യാസപ്പെടും',
    evidence: 'MEDIUM',
    description: 'Known for its rich, deep red color and strong growth habit in tropical regions.',
    descriptionML: 'ഗാഢമായ ചുവപ്പ് നിറത്തിനും ഉഷ്ണമേഖലാ പ്രദേശങ്ങളിലെ ശക്തമായ വളർച്ചയ്ക്കും പ്രശസ്തം.',
    plantNotes: 'Strong growth habit. Suitable for tropical conditions.',
    plantNotesML: 'ശക്തമായ വളർച്ച. ഉഷ്ണമേഖലാ പ്രദേശങ്ങൾക്ക് അനുയോജ്യം.',
    fruitNotes: 'Highly pigmented. Selection-dependent characteristics.',
    fruitNotesML: 'ഉയർന്ന നിറമുള്ള പഴം.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/malaysian-red-cut.jpg',
    altText: 'Malaysian Red dragon fruit cut open showing deep red flesh with black seeds'
  },
  {
    id: 'american-beauty',
    number: 7,
    name: 'American Beauty',
    nameML: 'അമേരിക്കൻ ബ്യൂട്ടി',
    character: 'Rich berry-like sweetness, vivid magenta',
    characterML: 'ബെറി രുചിയുള്ള മധുരം, ഉജ്ജ്വല മജന്ത',
    mainFeature: 'Vivid magenta flesh + widely reported self-fertility',
    mainFeatureML: 'ഉജ്ജ്വല മജന്ത ഉൾഭാഗം + വ്യാപകമായി റിപ്പോർട്ട് ചെയ്യപ്പെട്ട സ്വയം പരാഗണ ശേഷി',
    skin: 'Bright pink-red',
    skinML: 'തിളക്കമുള്ള പിങ്ക്-ചുവപ്പ്',
    flesh: 'Vivid fuchsia-magenta',
    fleshML: 'ഉജ്ജ്വല ഫ്യൂഷ-മജന്ത',
    flavor: 'Berry-like, complex',
    flavorML: 'ബെറി രുചി, സങ്കീർണ്ണം',
    brix: '17–19°',
    brixNote: 'Reported range — UC ANR trials report ~18.5°',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Self-fertile — widely reported',
    pollinationML: 'സ്വയം പരാഗണം — വ്യാപകമായി റിപ്പോർട്ട് ചെയ്തത്',
    evidence: 'HIGH',
    description: 'An incredibly popular commercial variety offering gorgeous fuchsia-magenta flesh and an excellent berry flavor.',
    descriptionML: 'മനോഹരമായ ഫ്യൂഷ-മജന്ത ഉൾഭാഗവും മികച്ച ബെറി രുചിയുമുള്ള ജനപ്രിയ വാണിജ്യ ഇനം.',
    plantNotes: 'Popular commercial variety. Reliable producer.',
    plantNotesML: 'ജനപ്രിയ വാണിജ്യ ഇനം. വിശ്വസനീയമായ വിളവ്.',
    fruitNotes: 'Medium to large fruit. Excellent color and flavor.',
    fruitNotesML: 'ഇടത്തരം മുതൽ വലിയ പഴം വരെ. മികച്ച നിറവും രുചിയും.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/american-beauty-cut.jpg',
    altText: 'American Beauty dragon fruit cut open showing vivid fuchsia-magenta flesh with black seeds'
  },
  {
    id: 'israel-yellow',
    number: 8,
    name: 'Israel Yellow',
    nameML: 'ഇസ്രായേൽ യെല്ലോ',
    character: 'Smooth yellow skin, mild sweet white flesh',
    characterML: 'മിനുസമുള്ള മഞ്ഞ തൊലി, സൗമ്യ മധുരം',
    mainFeature: 'Smooth yellow skin + white flesh (distinct from Palora)',
    mainFeatureML: 'മിനുസമുള്ള മഞ്ഞ തൊലി + വെളുത്ത ഉൾഭാഗം (പലോറയിൽ നിന്ന് വ്യത്യസ്തം)',
    skin: 'Yellow, smooth',
    skinML: 'മഞ്ഞ, മിനുസമുള്ള തൊലി',
    flesh: 'White',
    fleshML: 'വെളുത്ത ഉൾഭാഗം',
    flavor: 'Sweet, mild',
    flavorML: 'മധുരം, സൗമ്യം',
    brix: '14–16°',
    brixNote: 'Reported range',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Self-incompatible',
    pollinationML: 'അന്യ പരാഗണം ആവശ്യമാണ്',
    evidence: 'MEDIUM',
    description: 'A rare smooth-skinned yellow variety producing sweet, white flesh. Requires cross-pollination.',
    descriptionML: 'മിനുസമുള്ള മഞ്ഞ തൊലിയും മധുരമുള്ള വെള്ള ഉൾഭാഗവും ഉള്ള അപൂർവ ഇനം. ഫലം ഉണ്ടാകാൻ അന്യ പരാഗണം ആവശ്യമാണ്.',
    plantNotes: 'Requires companion varieties for pollination.',
    plantNotesML: 'പരാഗണത്തിന് മറ്റ് ഇനങ്ങൾ ആവശ്യമാണ്.',
    fruitNotes: 'Large fruit with smooth yellow skin. Distinct from thorny Ecuador Palora.',
    fruitNotesML: 'മിനുസമുള്ള മഞ്ഞ തൊലിയുള്ള വലിയ പഴം.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/israel-yellow-cut.jpg',
    altText: 'Israel Yellow dragon fruit cut open showing white flesh with black seeds and smooth yellow skin'
  },
  {
    id: 'costa-rican-white',
    number: 9,
    name: 'Costa Rican White',
    nameML: 'കോസ്റ്റാ റിക്കൻ വൈറ്റ്',
    character: 'Classic white-fleshed, refreshing and reliable',
    characterML: 'ക്ലാസിക് വെളുത്ത ഉൾഭാഗം, ഉന്മേഷദായകം',
    mainFeature: 'Fast-growing reliable producer + crisp refreshing flavor',
    mainFeatureML: 'വേഗത്തിൽ വളരുന്ന വിശ്വസനീയ ഇനം + മൊരുമൊരുപ്പുള്ള ഉന്മേഷദായക രുചി',
    skin: 'Red-pink',
    skinML: 'ചുവപ്പ്-പിങ്ക്',
    flesh: 'White',
    fleshML: 'വെളുത്ത ഉൾഭാഗം',
    flavor: 'Refreshing, crisp',
    flavorML: 'ഉന്മേഷദായകം, മൊരുമൊരുപ്പ്',
    brix: '12–15°',
    brixNote: 'Reported range',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Self-fertile — widely reported',
    pollinationML: 'സ്വയം പരാഗണം — വ്യാപകമായി റിപ്പോർട്ട് ചെയ്തത്',
    evidence: 'HIGH',
    description: 'The classic white-fleshed dragon fruit. Very reliable, fast-growing, and highly productive.',
    descriptionML: 'ക്ലാസിക് വെളുത്ത ഉൾഭാഗമുള്ള ഡ്രാഗൺ ഫ്രൂട്ട്. വിശ്വസനീയം, വേഗം വളരുന്നത്, മികച്ച വിളവ്.',
    plantNotes: 'Fast-growing. Reliable producer. Good for beginners.',
    plantNotesML: 'വേഗത്തിൽ വളരുന്നു. തുടക്കക്കാർക്ക് അനുയോജ്യം.',
    fruitNotes: 'Medium to large fruit. Clean, refreshing flavor.',
    fruitNotesML: 'ഇടത്തരം മുതൽ വലിയ പഴം വരെ. ഉന്മേഷദായകമായ രുചി.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/costa-rican-white-cut.jpg',
    altText: 'Costa Rican White dragon fruit cut open showing white flesh with black seeds and pink-red skin'
  },
  {
    id: 'super-nova',
    number: 10,
    name: 'Super Nova',
    nameML: 'സൂപ്പർ നോവ',
    character: 'Intensely sweet with gradient pink-white flesh',
    characterML: 'തീവ്ര മധുരം, ഗ്രേഡിയന്റ് പിങ്ക്-വെളുപ്പ്',
    mainFeature: 'Intensely sweet reported flavor + distinctive pink-white gradient flesh',
    mainFeatureML: 'തീവ്ര മധുരം + വ്യതിരിക്തമായ പിങ്ക്-വെളുപ്പ് ഗ്രേഡിയന്റ് ഉൾഭാഗം',
    skin: 'Pinkish red',
    skinML: 'പിങ്ക് കലർന്ന ചുവപ്പ്',
    flesh: 'Pink-to-white gradient',
    fleshML: 'പിങ്ക്-വെളുപ്പ് ഗ്രേഡിയന്റ്',
    flavor: 'Intensely sweet',
    flavorML: 'തീവ്ര മധുരം',
    brix: '17–19°',
    brixNote: 'Reported — limited cultivar-specific published data',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Cross-pollination recommended',
    pollinationML: 'അന്യ പരാഗണം ശുപാർശ ചെയ്യുന്നു',
    evidence: 'LIMITED',
    description: 'A premium variety celebrated for its intense sweetness and beautiful large fruit with gradient flesh.',
    descriptionML: 'തീവ്ര മധുരത്തിനും മനോഹരമായ വലിയ ഫലത്തിനും ആഘോഷിക്കപ്പെടുന്ന പ്രീമിയം ഇനം.',
    plantNotes: 'Requires companion varieties for pollination.',
    plantNotesML: 'പരാഗണത്തിന് മറ്റ് ഇനങ്ങൾ ആവശ്യമാണ്.',
    fruitNotes: 'Large fruit. Limited published cultivar data.',
    fruitNotesML: 'വലിയ ഫലം. തീവ്ര മധുരം.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/super-nova-cut.jpg',
    altText: 'Super Nova dragon fruit cut open showing pink-to-white gradient flesh with black seeds'
  },
  {
    id: 'natural-mystic',
    number: 11,
    name: 'Natural Mystic',
    nameML: 'നാച്ചുറൽ മിസ്റ്റിക്',
    character: 'Balanced sweet red, adaptable grower',
    characterML: 'സന്തുലിത മധുരം, അനുയോജ്യ വളർച്ച',
    mainFeature: 'Balanced sweet red + adaptable commercial/home grower',
    mainFeatureML: 'സന്തുലിത മധുരം + വാണിജ്യ/ഗാർഹിക കൃഷിക്ക് അനുയോജ്യം',
    skin: 'Red',
    skinML: 'ചുവപ്പ്',
    flesh: 'Red-pink',
    fleshML: 'ചുവപ്പ്-പിങ്ക്',
    flavor: 'Sweet, balanced',
    flavorML: 'മധുരം, സന്തുലിതം',
    brix: '15–17°',
    brixNote: 'Reported range',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി',
    pollination: 'Self-fertile — reported',
    pollinationML: 'സ്വയം പരാഗണം — റിപ്പോർട്ട് ചെയ്തത്',
    evidence: 'MEDIUM',
    description: 'A highly adaptable and reliable red variety producing well-rounded, sweet fruit.',
    descriptionML: 'വളരെ അനുയോജ്യവും വിശ്വസനീയവുമായ ചുവന്ന ഇനം. സന്തുലിതമായ മധുര രുചിയുള്ള നല്ല ഫലം ഉൽപ്പാദിപ്പിക്കുന്നു.',
    plantNotes: 'Highly adaptable. Suitable for various growing conditions.',
    plantNotesML: 'വളരെ അനുയോജ്യം. വിവിധ സാഹചര്യങ്ങളിൽ വളർത്താം.',
    fruitNotes: 'Well-rounded flavor. Good for fresh eating.',
    fruitNotesML: 'സന്തുലിതമായ രുചി. നേരിട്ട് കഴിക്കാൻ മികച്ചത്.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/natural-mystic-cut.jpg',
    altText: 'Natural Mystic dragon fruit cut open showing red-pink flesh with black seeds'
  },
  {
    id: 'thompson',
    number: 12,
    name: 'Thompson',
    nameML: 'തോംസൺ',
    character: 'Large fruit, crisp sweet, strong vigor',
    characterML: 'വലിയ ഫലം, മൊരുമൊരുപ്പുള്ള മധുരം',
    mainFeature: 'Large crisp fruit + strong plant vigor (requires cross-pollination)',
    mainFeatureML: 'വലിയ മൊരുമൊരുപ്പുള്ള ഫലം + ശക്തമായ വളർച്ച (അന്യ പരാഗണം ആവശ്യമാണ്)',
    skin: 'Red',
    skinML: 'ചുവപ്പ്',
    flesh: 'Pink-red',
    fleshML: 'പിങ്ക്-ചുവപ്പ്',
    flavor: 'Sweet, crisp',
    flavorML: 'മധുരം, മൊരുമൊരുപ്പ്',
    brix: '16–18°',
    brixNote: 'Reported range — may vary by clone',
    brixNoteML: 'റിപ്പോർട്ട് ചെയ്ത പരിധി — ക്ലോൺ അനുസരിച്ച് വ്യത്യാസപ്പെടും',
    pollination: 'Self-incompatible — reported',
    pollinationML: 'അന്യ പരാഗണം ആവശ്യമാണ്',
    evidence: 'MEDIUM',
    description: 'A beautiful large-fruited variety with crisp, sweet flesh and strong vigor. Requires cross-pollination.',
    descriptionML: 'മൊരുമൊരുപ്പുള്ള, മധുരമുള്ള ഉൾഭാഗവും ശക്തമായ വളർച്ചയുമുള്ള വലിയ ഇനം. അന്യ പരാഗണം ആവശ്യമാണ്.',
    plantNotes: 'Strong vigor. Requires companion varieties.',
    plantNotesML: 'ശക്തമായ വളർച്ച. മറ്റ് ഇനങ്ങൾ ആവശ്യമാണ്.',
    fruitNotes: 'Large fruit. Clone-dependent characteristics.',
    fruitNotesML: 'വലിയ ഫലം. ക്ലോൺ അനുസരിച്ച് മാറും.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/thompson-cut.jpg',
    altText: 'Thompson dragon fruit cut open showing pink-red flesh with black seeds'
  },
  {
    id: 'voodoo-child',
    number: 13,
    name: 'Voodoo Child',
    nameML: 'വൂഡൂ ചൈൽഡ്',
    character: 'Intensely sweet, raspberry-like, concentrated',
    characterML: 'തീവ്ര മധുരം, റാസ്‌ബെറി രുചി',
    mainFeature: 'Exceptionally high reported sweetness + concentrated raspberry flavor',
    mainFeatureML: 'ഉയർന്ന മധുരം + തീവ്രമായ റാസ്‌ബെറി രുചി',
    skin: 'Red',
    skinML: 'ചുവപ്പ്',
    flesh: 'Dark red-purple',
    fleshML: 'ഇരുണ്ട ചുവപ്പ്-പർപ്പിൾ',
    flavor: 'Intensely sweet, raspberry-like',
    flavorML: 'തീവ്ര മധുരം, റാസ്‌ബെറി രുചി',
    brix: '19–21°',
    brixNote: 'Specialist-reported — among the sweetest selections',
    brixNoteML: 'സ്പെഷ്യലിസ്റ്റ് റിപ്പോർട്ട് — ഏറ്റവും മധുരമുള്ള ഇനങ്ങളിൽ ഒന്ന്',
    pollination: 'Self-fertile — reported',
    pollinationML: 'സ്വയം പരാഗണം — റിപ്പോർട്ട് ചെയ്തത്',
    evidence: 'MEDIUM',
    description: 'Produces exceptionally sweet fruits with concentrated dark red-purple flesh and raspberry-like notes.',
    descriptionML: 'അസാധാരണമായ മധുരമുള്ള, ഇരുണ്ട ചുവപ്പ്-പർപ്പിൾ ഉൾഭാഗവും റാസ്‌ബെറി രുചിയുമുള്ള ഫലങ്ങൾ.',
    plantNotes: 'Collector variety. Smaller fruit but exceptional flavor concentration.',
    plantNotesML: 'പ്രത്യേക ശേഖരത്തിലുള്ള ഇനം. ചെറിയ ഫലമെങ്കിലും മികച്ച രുചി.',
    fruitNotes: 'Small to medium fruit. Intensely concentrated sweetness.',
    fruitNotesML: 'ചെറുത് മുതൽ ഇടത്തരം വരെ ഫലം. തീവ്ര മധുരം.',
    availability: 'Plants and cuttings available',
    availabilityML: 'ചെടികളും കട്ടിംഗുകളും ലഭ്യമാണ്',
    image: 'assets/images/varieties/voodoo-child-cut.jpg',
    altText: 'Voodoo Child dragon fruit cut open showing dark red-purple flesh with black seeds'
  }
];


/**
 * Generate a WhatsApp order URL for a specific product and variety
 */
function getWhatsAppURL(varietyName, productType) {
  const messages = {
    plant: `Hello HomeFarm,%0AI would like to order a ${varietyName} rooted dragon-fruit plant.%0APlease share availability and details.`,
    cutting: `Hello HomeFarm,%0AI would like to order a ${varietyName} fresh live cutting.%0APlease share availability and details.`,
    fruit: `Hello HomeFarm,%0AI am interested in fresh ${varietyName} dragon fruit.%0APlease let me know about seasonal availability.`,
    general: `Hello HomeFarm,%0AI would like to know more about your dragon fruit plants and varieties.%0APlease share details.`
  };
  const msg = messages[productType] || messages.general;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`;
}

